function REPORT = compare_XNSRCalibration(generatedPath,calibrationPath)
%COMPARE_XNSRCALIBRATION Compare an XNSR output with its reference MAT file.
%   REPORT = COMPARE_XNSRCALIBRATION(GENERATEDPATH) selects the reference
%   from DataCalib/Triang or DataCalib/KonnoOhmachi according to the
%   smoothing method stored in GENERATEDPATH.
%
%   REPORT = COMPARE_XNSRCALIBRATION(GENERATEDPATH,CALIBRATIONPATH) uses an
%   explicit reference file. Scientific numeric fields are compared with
%   floating-point tolerances; graphics handles and other session-specific
%   values are intentionally ignored.

narginchk(1,2);
generatedPath = char(generatedPath);

assert(isfile(generatedPath), ...
    'XNSR:CalibrationComparison:MissingGeneratedFile', ...
    'Generated MAT file not found: %s',generatedPath);

generatedFile = load(generatedPath,'XN_DATA');
assert(isfield(generatedFile,'XN_DATA') && isstruct(generatedFile.XN_DATA), ...
    'XNSR:CalibrationComparison:InvalidGeneratedFile', ...
    '%s does not contain a valid XN_DATA structure.',generatedPath);
generated = generatedFile.XN_DATA;

if nargin < 2 || isempty(calibrationPath)
    softwarePath = fileparts(mfilename('fullpath'));
    repositoryPath = fileparts(softwarePath);
    [~,datasetName] = fileparts(generatedPath);
    smoothingType = upper(generated.PARAM.SCRIPT.SMOOTHING_WIN_TYPE);
    switch smoothingType
        case 'T'
            calibrationFamily = 'Triang';
        case 'K'
            calibrationFamily = 'KonnoOhmachi';
        otherwise
            error('XNSR:CalibrationComparison:UnknownSmoothingType', ...
                'Unsupported smoothing type: %s',smoothingType);
    end
    calibrationPath = fullfile(repositoryPath,'DataCalib', ...
        calibrationFamily,[datasetName '.mat']);
else
    calibrationPath = char(calibrationPath);
end

assert(isfile(calibrationPath), ...
    'XNSR:CalibrationComparison:MissingCalibrationFile', ...
    'Calibration MAT file not found: %s',calibrationPath);

calibrationFile = load(calibrationPath,'XN_DATA');
assert(isfield(calibrationFile,'XN_DATA') && ...
    isstruct(calibrationFile.XN_DATA), ...
    'XNSR:CalibrationComparison:InvalidCalibrationFile', ...
    '%s does not contain a valid XN_DATA structure.',calibrationPath);
reference = calibrationFile.XN_DATA;

assert(generated.PARAM.SCRIPT.SMOOTHING_WIN_TYPE == ...
    reference.PARAM.SCRIPT.SMOOTHING_WIN_TYPE, ...
    'XNSR:CalibrationComparison:SmoothingTypeMismatch', ...
    'Generated and reference files use different smoothing methods.');

fieldNames = { ...
    'HV_RATIO','HV_RATIO_Fc','HV_STD','MAX_HV_RATIO','MAX_HV_F', ...
    'ALPHA_VEC','THETA_VEC','TXYZ'};
absoluteTolerance = 1e-10;
relativeTolerance = 1e-8;
maximumAbsoluteDifference = zeros(size(fieldNames));
maximumRelativeDifference = zeros(size(fieldNames));

for fieldIndex = 1:numel(fieldNames)
    fieldName = fieldNames{fieldIndex};
    assert(isfield(generated,fieldName) && isfield(reference,fieldName), ...
        'XNSR:CalibrationComparison:MissingField', ...
        'Scientific field %s is missing.',fieldName);

    actual = generated.(fieldName);
    expected = reference.(fieldName);
    assert(isequal(size(actual),size(expected)), ...
        'XNSR:CalibrationComparison:SizeMismatch', ...
        'Field %s has different dimensions.',fieldName);

    finiteMask = isfinite(actual) & isfinite(expected);
    matchingNonfinite = (~finiteMask) & ...
        ((isnan(actual) & isnan(expected)) | (actual == expected));
    difference = abs(actual - expected);
    allowedDifference = absoluteTolerance + ...
        relativeTolerance .* abs(expected);
    matchingFinite = finiteMask & (difference <= allowedDifference);
    assert(all(matchingFinite(:) | matchingNonfinite(:)), ...
        'XNSR:CalibrationComparison:ValueMismatch', ...
        'Field %s differs from its calibration beyond tolerance.',fieldName);

    if any(finiteMask(:))
        finiteDifference = difference(finiteMask);
        finiteReference = abs(expected(finiteMask));
        maximumAbsoluteDifference(fieldIndex) = max(finiteDifference);
        maximumRelativeDifference(fieldIndex) = max(finiteDifference ./ ...
            max(finiteReference,absoluteTolerance));
    end
end

REPORT = struct( ...
    'generatedPath',generatedPath, ...
    'calibrationPath',calibrationPath, ...
    'fields',{fieldNames}, ...
    'maximumAbsoluteDifference',maximumAbsoluteDifference, ...
    'maximumRelativeDifference',maximumRelativeDifference, ...
    'absoluteTolerance',absoluteTolerance, ...
    'relativeTolerance',relativeTolerance, ...
    'passed',true);

fprintf(['CONFRONTO DATACALIB SUPERATO\n', ...
    'Output:      %s\n', ...
    'Riferimento: %s\n', ...
    'Differenza assoluta massima: %.3g\n'], ...
    generatedPath,calibrationPath,max(maximumAbsoluteDifference));
end
