function [XN_DATA, outputPath] = generate_KonnoOhmachiCalibration(datasetName)
%GENERATE_KONNOOHMACHICALIBRATION Generate one versioned XNSR reference.
%   XN_DATA = GENERATE_KONNOOHMACHICALIBRATION(NAME) processes one of the
%   nine bundled datasets using Konno-Ohmachi smoothing and writes the
%   result to DataCalib/KonnoOhmachi/NAME.mat.

arguments
    datasetName (1,1) string
end

softwarePath = fileparts(mfilename('fullpath'));
repositoryPath = fileparts(softwarePath);
dataPath = fullfile(repositoryPath,'DataIn');
outputDirectory = fullfile(repositoryPath,'DataCalib','KonnoOhmachi');
configPath = fullfile(repositoryPath,'Cfg','XN_Cruncher_Konno.cfg');

datasetName = validatestring(datasetName, { ...
    'CA04', ...
    'Edificio_Dorando', ...
    'Ferrara', ...
    'Lorca_001', ...
    'Lorca_002', ...
    'Polignano', ...
    'sanGiuliano_001', ...
    'sanGiuliano_002', ...
    'ValMontanaia_001'});

switch datasetName
    case 'CA04'
        inputNames = { ...
            '2004183110000.00.CA04.EHE.vel', ...
            '2004183110000.00.CA04.EHN.vel', ...
            '2004183110000.00.CA04.EHZ.vel'};
    case 'Edificio_Dorando'
        inputNames = { ...
            'Edificio_Dorando_E-W.trc', ...
            'Edificio_Dorando_N-S.trc', ...
            'Edificio_Dorando_Z.trc'};
    case 'Ferrara'
        inputNames = {'Ferrara_EW.dat','Ferrara_NS.dat','Ferrara_Z.dat'};
    case 'Lorca_001'
        inputNames = { ...
            'Lorca_001_E-W.trc','Lorca_001_N-S.trc','Lorca_001_Z.trc'};
    case 'Lorca_002'
        inputNames = { ...
            'Lorca_002_E-W.trc','Lorca_002_N-S.trc','Lorca_002_Z.trc'};
    case 'Polignano'
        inputNames = {'Polignano_we.dat','Polignano_ns.dat','Polignano_up.dat'};
    case 'sanGiuliano_001'
        inputNames = { ...
            'sanGiuliano_001_E-W.trc', ...
            'sanGiuliano_001_N-S.trc', ...
            'sanGiuliano_001_Z.trc'};
    case 'sanGiuliano_002'
        inputNames = { ...
            'sanGiuliano_002_E-W.trc', ...
            'sanGiuliano_002_N-S.trc', ...
            'sanGiuliano_002_Z.trc'};
    case 'ValMontanaia_001'
        inputNames = { ...
            'ValMontanaia_001_E-W.trc', ...
            'ValMontanaia_001_N-S.trc', ...
            'ValMontanaia_001_Z.trc'};
end

fileList = cellfun(@(name) fullfile(dataPath,name),inputNames, ...
    'UniformOutput',false);
assert(all(cellfun(@isfile,fileList)), ...
    'XNSR:KonnoCalibration:MissingInput', ...
    'One or more input files for %s are missing.',datasetName);
assert(isfile(configPath), ...
    'XNSR:KonnoCalibration:MissingConfig', ...
    'The Konno-Ohmachi configuration file is missing.');

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
outputPath = fullfile(outputDirectory,[datasetName '.mat']);

pool = gcp('nocreate');
if isempty(pool)
    pool = parpool;
end

calibrationTimer = tic;
XN_DATA = XN_Cruncher(fileList,outputPath,configPath);
elapsedSeconds = toc(calibrationTimer);

assert(isfile(outputPath), ...
    'XNSR:KonnoCalibration:MissingOutput', ...
    'XN_Cruncher did not create %s.',outputPath);
assert(XN_DATA.PARAM.SCRIPT.SMOOTHING_WIN_TYPE == 'K');
assert(XN_DATA.PARAM.KONNO.b == 40);
assert(ismember(upper(XN_DATA.PARAM.SCRIPT.CALCULUS_MODE),{'M','MIXED'}));

numericFields = { ...
    'HV_RATIO','HV_RATIO_Fc','HV_STD','MAX_HV_RATIO','MAX_HV_F', ...
    'ALPHA_VEC','THETA_VEC','TXYZ'};
for fieldIndex = 1:numel(numericFields)
    fieldName = numericFields{fieldIndex};
    values = XN_DATA.(fieldName);
    assert(isnumeric(values) && ~isempty(values), ...
        'XNSR:KonnoCalibration:InvalidField', ...
        'XN_DATA.%s must be a nonempty numeric array.',fieldName);
    assert(all(isfinite(values(:))), ...
        'XNSR:KonnoCalibration:NonfiniteField', ...
        'XN_DATA.%s contains NaN or Inf.',fieldName);
end

alphaCount = floor(XN_DATA.PARAM.GEOM.MAX_ALPHA / ...
    XN_DATA.PARAM.GEOM.STEP_ALPHA) + 1;
thetaCount = floor(XN_DATA.PARAM.GEOM.MAX_THETA / ...
    XN_DATA.PARAM.GEOM.STEP_THETA) + 1;
orientationCount = alphaCount * thetaCount;
assert(size(XN_DATA.HV_RATIO,3) == orientationCount);
assert(numel(XN_DATA.MAX_HV_RATIO) == orientationCount);
assert(numel(XN_DATA.MAX_HV_F) == orientationCount);

fprintf(['KONNO-OHMACHI CALIBRATION SUPERATA: %s | ', ...
    '%d workers | %.3f s | %s\n'], ...
    datasetName,pool.NumWorkers,elapsedSeconds,outputPath);
end
