function [datasetName,fileList,repositoryPath] = ...
    get_XNSRDatasetFiles(datasetName)
%GET_XNSRDATASETFILES Resolve one bundled experiment to its input files.

arguments
    datasetName (1,1) string
end

datasetName = string(validatestring(datasetName, { ...
    'CA04', ...
    'Edificio_Dorando', ...
    'Ferrara', ...
    'Lorca_001', ...
    'Lorca_002', ...
    'Polignano', ...
    'sanGiuliano_001', ...
    'sanGiuliano_002', ...
    'ValMontanaia_001'}));

switch datasetName
    case "CA04"
        inputNames = { ...
            '2004183110000.00.CA04.EHE.vel', ...
            '2004183110000.00.CA04.EHN.vel', ...
            '2004183110000.00.CA04.EHZ.vel'};
    case "Edificio_Dorando"
        inputNames = { ...
            'Edificio_Dorando_E-W.trc', ...
            'Edificio_Dorando_N-S.trc', ...
            'Edificio_Dorando_Z.trc'};
    case "Ferrara"
        inputNames = {'Ferrara_EW.dat','Ferrara_NS.dat','Ferrara_Z.dat'};
    case "Lorca_001"
        inputNames = { ...
            'Lorca_001_E-W.trc','Lorca_001_N-S.trc','Lorca_001_Z.trc'};
    case "Lorca_002"
        inputNames = { ...
            'Lorca_002_E-W.trc','Lorca_002_N-S.trc','Lorca_002_Z.trc'};
    case "Polignano"
        inputNames = {'Polignano_we.dat','Polignano_ns.dat','Polignano_up.dat'};
    case "sanGiuliano_001"
        inputNames = { ...
            'sanGiuliano_001_E-W.trc', ...
            'sanGiuliano_001_N-S.trc', ...
            'sanGiuliano_001_Z.trc'};
    case "sanGiuliano_002"
        inputNames = { ...
            'sanGiuliano_002_E-W.trc', ...
            'sanGiuliano_002_N-S.trc', ...
            'sanGiuliano_002_Z.trc'};
    case "ValMontanaia_001"
        inputNames = { ...
            'ValMontanaia_001_E-W.trc', ...
            'ValMontanaia_001_N-S.trc', ...
            'ValMontanaia_001_Z.trc'};
end

softwarePath = fileparts(mfilename('fullpath'));
repositoryPath = fileparts(softwarePath);
dataPath = fullfile(repositoryPath,'DataIn');
fileList = cellfun(@(name) fullfile(dataPath,name),inputNames, ...
    'UniformOutput',false);

assert(all(cellfun(@isfile,fileList)), ...
    'XNSR:Dataset:MissingInput', ...
    'One or more input files for %s are missing.',datasetName);
end
