function [XN_DATA, outputPath] = update_XNSRCalibration( ...
    datasetName,smoothingMethod)
%UPDATE_XNSRCALIBRATION Create or replace one official XNSR reference.
%   XN_DATA = UPDATE_XNSRCALIBRATION(NAME,METHOD) processes one of the nine
%   bundled datasets by calling XN_Cruncher and writes the result to the
%   corresponding DataCalib subdirectory.
%
%   METHOD can be "Triang" or "KonnoOhmachi". This maintenance function
%   overwrites an official reference and is not intended as a regression
%   test. Use test_XN_Cruncher_<dataset>.m to write to DataOut and compare
%   a new result without modifying DataCalib.

arguments
    datasetName (1,1) string
    smoothingMethod (1,1) string
end

datasetName = validatestring(datasetName, { ...
    'CA04', ...
    'Edificio_Dorando', ...
    'Ferrara', ...
    'Lorca_001', ...
    'Lorca_002', ...
    'Polignano', ...
    'sanGiuliano_001', ...
    'sanGiuliano_002', ...
    'ValMontanaia_001'});
smoothingMethod = validatestring(smoothingMethod, ...
    {'Triang','KonnoOhmachi'});

softwarePath = fileparts(mfilename('fullpath'));
repositoryPath = fileparts(softwarePath);
dataPath = fullfile(repositoryPath,'DataIn');

switch smoothingMethod
    case 'Triang'
        outputFamily = 'Triang';
        configName = 'XN_Cruncher_Triang.cfg';
        expectedSmoothingType = 'T';
    case 'KonnoOhmachi'
        outputFamily = 'KonnoOhmachi';
        configName = 'XN_Cruncher_Konno.cfg';
        expectedSmoothingType = 'K';
end

outputDirectory = fullfile(repositoryPath,'DataCalib',outputFamily);
configPath = fullfile(repositoryPath,'Cfg',configName);
inputNames = calibrationInputNames(datasetName);
fileList = cellfun(@(name) fullfile(dataPath,name),inputNames, ...
    'UniformOutput',false);

assert(all(cellfun(@isfile,fileList)), ...
    'XNSR:CalibrationUpdate:MissingInput', ...
    'One or more input files for %s are missing.',datasetName);
assert(isfile(configPath), ...
    'XNSR:CalibrationUpdate:MissingConfig', ...
    'Calibration configuration file not found: %s',configPath);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
outputPath = fullfile(outputDirectory,[datasetName '.mat']);

pool = gcp('nocreate');
if isempty(pool)
    pool = parpool;
end

calibrationTimer = tic;
XN_DATA = XN_Cruncher(fileList,outputPath,configPath);
elapsedSeconds = toc(calibrationTimer);

assert(isfile(outputPath), ...
    'XNSR:CalibrationUpdate:MissingOutput', ...
    'XN_Cruncher did not create %s.',outputPath);
assert(XN_DATA.PARAM.SCRIPT.SMOOTHING_WIN_TYPE == expectedSmoothingType, ...
    'XNSR:CalibrationUpdate:WrongSmoothingType', ...
    'XN_Cruncher used an unexpected smoothing method.');
if expectedSmoothingType == 'K'
    assert(XN_DATA.PARAM.KONNO.b == 40, ...
        'XNSR:CalibrationUpdate:WrongKonnoParameter', ...
        'The Konno-Ohmachi reference must use b = 40.');
else
    assert(XN_DATA.PARAM.TRIANG.perc == 3, ...
        'XNSR:CalibrationUpdate:WrongTriangParameter', ...
        'The triangular reference must use a 3%% window.');
end
assert(ismember(upper(XN_DATA.PARAM.SCRIPT.CALCULUS_MODE),{'M','MIXED'}));

numericFields = { ...
    'HV_RATIO','HV_RATIO_Fc','HV_STD','MAX_HV_RATIO','MAX_HV_F', ...
    'ALPHA_VEC','THETA_VEC','TXYZ'};
for fieldIndex = 1:numel(numericFields)
    fieldName = numericFields{fieldIndex};
    assert(isfield(XN_DATA,fieldName), ...
        'XNSR:CalibrationUpdate:MissingField', ...
        'XN_DATA.%s is missing.',fieldName);
    values = XN_DATA.(fieldName);
    assert(isnumeric(values) && ~isempty(values), ...
        'XNSR:CalibrationUpdate:InvalidField', ...
        'XN_DATA.%s must be a nonempty numeric array.',fieldName);
    assert(all(isfinite(values(:))), ...
        'XNSR:CalibrationUpdate:NonfiniteField', ...
        'XN_DATA.%s contains NaN or Inf.',fieldName);
end

alphaCount = floor(XN_DATA.PARAM.GEOM.MAX_ALPHA / ...
    XN_DATA.PARAM.GEOM.STEP_ALPHA) + 1;
thetaCount = floor(XN_DATA.PARAM.GEOM.MAX_THETA / ...
    XN_DATA.PARAM.GEOM.STEP_THETA) + 1;
orientationCount = alphaCount * thetaCount;
assert(size(XN_DATA.HV_RATIO,3) == orientationCount);
assert(numel(XN_DATA.MAX_HV_RATIO) == orientationCount);
assert(numel(XN_DATA.MAX_HV_F) == orientationCount);

fprintf(['RIFERIMENTO DATACALIB AGGIORNATO: %s | %s | ', ...
    '%d workers | %.3f s\n%s\n'], ...
    datasetName,outputFamily,pool.NumWorkers,elapsedSeconds,outputPath);
end

function inputNames = calibrationInputNames(datasetName)
switch datasetName
    case 'CA04'
        inputNames = { ...
            '2004183110000.00.CA04.EHE.vel', ...
            '2004183110000.00.CA04.EHN.vel', ...
            '2004183110000.00.CA04.EHZ.vel'};
    case 'Edificio_Dorando'
        inputNames = { ...
            'Edificio_Dorando_E-W.trc', ...
            'Edificio_Dorando_N-S.trc', ...
            'Edificio_Dorando_Z.trc'};
    case 'Ferrara'
        inputNames = {'Ferrara_EW.dat','Ferrara_NS.dat','Ferrara_Z.dat'};
    case 'Lorca_001'
        inputNames = { ...
            'Lorca_001_E-W.trc','Lorca_001_N-S.trc','Lorca_001_Z.trc'};
    case 'Lorca_002'
        inputNames = { ...
            'Lorca_002_E-W.trc','Lorca_002_N-S.trc','Lorca_002_Z.trc'};
    case 'Polignano'
        inputNames = {'Polignano_we.dat','Polignano_ns.dat','Polignano_up.dat'};
    case 'sanGiuliano_001'
        inputNames = { ...
            'sanGiuliano_001_E-W.trc', ...
            'sanGiuliano_001_N-S.trc', ...
            'sanGiuliano_001_Z.trc'};
    case 'sanGiuliano_002'
        inputNames = { ...
            'sanGiuliano_002_E-W.trc', ...
            'sanGiuliano_002_N-S.trc', ...
            'sanGiuliano_002_Z.trc'};
    case 'ValMontanaia_001'
        inputNames = { ...
            'ValMontanaia_001_E-W.trc', ...
            'ValMontanaia_001_N-S.trc', ...
            'ValMontanaia_001_Z.trc'};
end
end
